name: defifundr_mobile
description: Crowdfunding app for DeFi projects
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  http: ^0.13.4
  curl_logger_dio_interceptor: ^0.0.1

dependencies:
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter

  currency_picker: ^2.0.21
  flutter:
    sdk: flutter
  #?  flutter_bloc is a Flutter package that helps you to easily implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^8.1.3
  #? flutter_form_bloc is a Flutter package that helps you to easily create forms with validation.
  bloc: any
  #? google_fonts is a Flutter package that provides a set of fonts from Google Fonts.
  google_fonts: ^5.0.0
  #?  flutter_screenutil is a Flutter package that provides a set of utilities for implementing responsive UI.
  flutter_screenutil: ^5.9.0
  #? flutter_svg is a Flutter package for drawing SVG pictures.
  flutter_svg: ^2.0.6
  #? Fluttertoast is a Flutter plugin to show toast.
  fluttertoast: ^8.1.1
  #?  go_router is a Flutter package that allows you to easily manage your app's navigation.
  go_router: ^8.0.1
  #? equatable is a Dart package that helps you to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5
  #? The email_validator package is a lightweight and efficient Dart package for validating email addresses in Flutter and Dart applications.
  email_validator: ^3.0.0
  #? freezed_annotation is a Dart package that provides a set of utilities for generating code for the freezed package.
  freezed_annotation: ^2.2.0
  #? shared_preferences is a Flutter plugin that provides a persistent store for simple data.
  shared_preferences: ^2.5.3


  flutter_native_splash: ^2.2.16
  get_it: ^8.0.3
  pinput: ^5.0.1
  country_picker: ^2.0.27
  country_list_pick: ^1.0.1+6
  intl: ^0.19.0
  carousel_slider: ^5.0.0

  file_picker: ^9.0.2
  bloc_concurrency: ^0.2.5
  nested: ^1.0.0
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.14.3"
  very_good_analysis: ^4.0.0+1
  #? freezed is a code generation library for Dart that helps you to write immutable models with ease.
  freezed: ^2.3.2
  #? build_runner is a Dart package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
  build_runner: ^2.3.3

#? For information on the generic Dart part of this file, see the
import_sorter:
  emojis: true

#? The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Thin.ttf
          weight: 100
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Black.ttf
          weight: 900
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_28pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_28pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_28pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_28pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_28pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_28pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_28pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_28pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_28pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_28pt-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo.png"
  android: true
  ios: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21