name: defifundr_mobile
description: Crowdfunding app for DeFi projects
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  http: ^0.13.4
  curl_logger_dio_interceptor: ^0.0.1

dependencies:
  cupertino_icons: ^1.0.2

  currency_picker: ^2.0.21
  flutter:
    sdk: flutter
  #?  flutter_bloc is a Flutter package that helps you to easily implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^8.1.3

  flutter_native_splash:
    ^2.2.16
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1

  



#? For information on the generic Dart part of this file, see the
import_sorter:
  emojis: true

#? The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    
flutter_native_splash:
  color: "#000000"
  image: "assets/images/splashLogo.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appLogo.png"
