import 'package:defifundr_mobile/core/design_system/theme_extension/app_theme_extension.dart';
import 'package:defifundr_mobile/core/shared/common_ui/appbar/appbar_header.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:go_router/go_router.dart';

class TwoFaAuthHeader extends StatelessWidget {
  const TwoFaAuthHeader({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        AppBarHeaderWidget(
          widget: IconButton(
            onPressed: () {
              context.pop();
            },
            icon: Icon(Icons.arrow_back_ios_new),
          ),
        ),
        SizedBox(height: 32.h),
        Text(
          '2FA Auth Code',
          style: context.theme.fonts.bodyMedium.copyWith(
            fontSize: 24.sp,
            color: context.theme.colors.textPrimary,
            fontWeight: FontWeight.w700,
          ),
        ),
        SizedBox(height: 4.h),
        Text(
          'Enter in the 6-digit code generated by the authenticator appn',
          style: context.theme.fonts.bodyMedium.copyWith(
            fontSize: 14.sp,
            fontWeight: FontWeight.w400,
            color: context.theme.colors.textSecondary,
          ),
        ),
      ],
    );
  }
}
