import 'package:defifundr_mobile/core/gen/fonts.gen.dart';
import 'package:flutter/material.dart';

import '../app_colors/app_colors.dart';
import '../color_extension/app_color_extension.dart';
import '../font_extension/font_extension.dart';

class AppTheme {
  static final _lightAppColorss = AppColorExtension(
    textPrimary: AppColors.textPrimary,
    textSecondary: AppColors.textSecondary,
    textTertiary: AppColors.textTertiary,
    textQuaternary: AppColors.textQuaternary,
    textWhite: AppColors.textWhite,
    constantDefault: AppColors.constantDefault,
    constantDefaultBorder: AppColors.constantDefaultBorder,
    brandDefault: AppColors.brandDefault,
    brandContrast: AppColors.brandContrast,
    brandDefaultContrast: AppColors.brandContrast,
    brandHover: AppColors.brandHover,
    brandActive: AppColors.brandActive,
    brandStroke: AppColors.brandStroke,
    brandFill: AppColors.brandFill,
    blueDefault: AppColors.blueDefault,
    blueHover: AppColors.blueHover,
    blueActive: AppColors.blueActive,
    blueStroke: AppColors.blueStroke,
    blueFill: AppColors.blueFill,
    greenDefault: AppColors.greenDefault,
    greenHover: AppColors.greenHover,
    greenActive: AppColors.greenActive,
    greenStroke: AppColors.greenStroke,
    greenFill: AppColors.greenFill,
    grayPrimary: AppColors.grayPrimary,
    graySecondary: AppColors.graySecondary,
    grayTertiary: AppColors.grayTertiary,
    grayQuaternary: AppColors.grayQuaternary,
    yellowDefault: AppColors.yellowDefault,
    yellowHover: AppColors.yellowHover,
    yellowActive: AppColors.yellowActive,
    yellowStroke: AppColors.yellowStroke,
    yellowFill: AppColors.yellowFill,
    orangeDefault: AppColors.orangeDefault,
    orangeHover: AppColors.orangeHover,
    orangeActive: AppColors.orangeActive,
    orangeStroke: AppColors.orangeStroke,
    orangeFill: AppColors.orangeFill,
    redDefault: AppColors.redDefault,
    redHover: AppColors.redHover,
    redActive: AppColors.redActive,
    redStroke: AppColors.redStroke,
    redFill: AppColors.redFill,
    pinkDefault: AppColors.pinkDefault,
    pinkHover: AppColors.pinkHover,
    pinkActive: AppColors.pinkActive,
    pinkStroke: AppColors.pinkStroke,
    pinkFill: AppColors.pinkFill,
    bgB0: AppColors.bgB0,
    bgB1: AppColors.bgB1,
    bgB2: AppColors.bgB2,
    bgB3: AppColors.bgB3,
    surface: AppColors.surface,
    surfaceCard: AppColors.surfaceCard,
    inactiveButton: AppColors.inactiveButton,
    activeButton: AppColors.activeButton,
    buttonTertiary: AppColors.buttonTertiary,
    buttonSecondary: AppColors.buttonSecondary,
    iconRed: AppColors.iconRed,
    iconBlue: AppColors.iconBlue,
    textHighlightBlue: AppColors.textHighlightBlue,
    contrastBlack: AppColors.contrastBlack,
    contrastWhite: AppColors.contrastWhite,
    strokePrimary: AppColorDark.strokePrimary,
    strokeSecondary: AppColors.strokeSecondary,
    fillTertiary: AppColors.fillTertiary,
  );

  static final _darkAppColorss = AppColorExtension(
    textPrimary: AppColorDark.textPrimary,
    textSecondary: AppColorDark.textSecondary,
    textTertiary: AppColorDark.textTertiary,
    textQuaternary: AppColorDark.textQuaternary,
    textWhite: AppColorDark.textWhite,
    constantDefault: AppColorDark.constantDefault,
    constantDefaultBorder: AppColorDark.constantDefaultBorder,
    brandDefault: AppColorDark.brandDefault,
    brandContrast: AppColorDark.brandContrast,
    brandDefaultContrast: AppColorDark.brandDefaultContrast,
    brandHover: AppColorDark.brandHover,
    brandActive: AppColorDark.brandActive,
    brandStroke: AppColorDark.brandStroke,
    brandFill: AppColorDark.brandFill,
    blueDefault: AppColorDark.blueDefault,
    blueHover: AppColorDark.blueHover,
    blueActive: AppColorDark.blueActive,
    blueStroke: AppColorDark.blueStroke,
    blueFill: AppColorDark.blueFill,
    greenDefault: AppColorDark.greenDefault,
    greenHover: AppColorDark.greenHover,
    greenActive: AppColorDark.greenActive,
    greenStroke: AppColorDark.greenStroke,
    greenFill: AppColorDark.greenFill,
    grayPrimary: AppColorDark.grayPrimary,
    graySecondary: AppColorDark.graySecondary,
    grayTertiary: AppColorDark.grayTertiary,
    grayQuaternary: AppColorDark.grayQuaternary,
    yellowDefault: AppColorDark.yellowDefault,
    yellowHover: AppColorDark.yellowHover,
    yellowActive: AppColorDark.yellowActive,
    yellowStroke: AppColorDark.yellowStroke,
    yellowFill: AppColorDark.yellowFill,
    orangeDefault: AppColorDark.orangeDefault,
    orangeHover: AppColorDark.orangeHover,
    orangeActive: AppColorDark.orangeActive,
    orangeStroke: AppColorDark.orangeStroke,
    orangeFill: AppColorDark.orangeFill,
    redDefault: AppColorDark.redDefault,
    redHover: AppColorDark.redHover,
    redActive: AppColorDark.redActive,
    redStroke: AppColorDark.redStroke,
    redFill: AppColorDark.redFill,
    pinkDefault: AppColorDark.pinkDefault,
    pinkHover: AppColorDark.pinkHover,
    pinkActive: AppColorDark.pinkActive,
    pinkStroke: AppColorDark.pinkStroke,
    pinkFill: AppColorDark.pinkFill,
    bgB0: AppColorDark.bgB0,
    bgB1: AppColorDark.bgB1,
    bgB2: AppColorDark.bgB2,
    bgB3: AppColorDark.bgB3,
    surface: AppColorDark.surface,
    surfaceCard: AppColorDark.surfaceCard,
    inactiveButton: AppColorDark.inactiveButton,
    activeButton: AppColorDark.activeButton,
    buttonTertiary: AppColorDark.buttonTertiary,
    buttonSecondary: AppColorDark.buttonSecondary,
    iconRed: AppColorDark.iconRed,
    iconBlue: AppColorDark.iconBlue,
    textHighlightBlue: AppColorDark.textHighlightBlue,
    contrastBlack: AppColorDark.contrastBlack,
    contrastWhite: AppColorDark.contrastWhite,
    strokePrimary: AppColorDark.strokePrimary,
    strokeSecondary: AppColorDark.strokeSecondary,
    fillTertiary: AppColorDark.fillTertiary,
  );

  static final _lightFontTheme = AppFontThemeExtension(
    heading1Bold: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading1SemiBold: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading1Medium: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading1Regular: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2Bold: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2SemiBold: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2Medium: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2Regular: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3Bold: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3SemiBold: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3Medium: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3Regular: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgBold: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgSemiBold: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgMedium: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgRegular: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseBold: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseSemiBold: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseMedium: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseRegular: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdBold: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdSemiBold: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdMedium: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdRegular: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmBold: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmSemiBold: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmMedium: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmRegular: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsBold: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsSemiBold: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w600,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsMedium: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w500,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsRegular: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    headerLarger: const TextStyle(
      fontSize: 28,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    headerSmall: const TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w700,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    subHeader: const TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      color: AppColors.textTertiary,
      fontFamily: FontFamily.inter,
    ),
    bodyMedium: const TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: AppColors.textPrimary,
      fontFamily: FontFamily.inter,
    ),
  );

  static final _darkFontTheme = AppFontThemeExtension(
    heading1Bold: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading1SemiBold: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading1Medium: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading1Regular: const TextStyle(
      fontSize: 32,
      height: 1.25,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2Bold: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2SemiBold: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2Medium: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading2Regular: const TextStyle(
      fontSize: 24,
      height: 1.33,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3Bold: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3SemiBold: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3Medium: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    heading3Regular: const TextStyle(
      fontSize: 20,
      height: 1.4,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgBold: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgSemiBold: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgMedium: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textLgRegular: const TextStyle(
      fontSize: 18,
      height: 1.33,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseBold: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseSemiBold: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseMedium: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textBaseRegular: const TextStyle(
      fontSize: 16,
      height: 1.5,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdBold: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdSemiBold: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdMedium: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textMdRegular: const TextStyle(
      fontSize: 14,
      height: 1.43,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmBold: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmSemiBold: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmMedium: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textSmRegular: const TextStyle(
      fontSize: 12,
      height: 1.33,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsBold: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsSemiBold: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w600,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsMedium: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w500,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    textXsRegular: const TextStyle(
      fontSize: 10,
      height: 1.4,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    headerLarger: const TextStyle(
      fontSize: 28,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    headerSmall: const TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w700,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
    subHeader: const TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textTertiary,
      fontFamily: FontFamily.inter,
    ),
    bodyMedium: const TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: AppColorDark.textPrimary,
      fontFamily: FontFamily.inter,
    ),
  );

  static final light = () {
    final defaultTheme = ThemeData.light();

    return defaultTheme.copyWith(
      colorScheme: _lightAppColorss.toColorScheme(Brightness.light),
      scaffoldBackgroundColor: _lightAppColorss.bgB1,
      appBarTheme: AppBarTheme(
        backgroundColor: _lightAppColorss.bgB0,
        titleTextStyle: _lightFontTheme.heading2Bold,
        elevation: 0,
      ),
      cardTheme: CardThemeData(
        color: _lightAppColorss.surfaceCard,
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8),
        ),
      ),
      textTheme: TextTheme(
        displayLarge: _lightFontTheme.heading1Bold,
        displayMedium: _lightFontTheme.heading2Bold,
        displaySmall: _lightFontTheme.heading3Bold,
        headlineLarge: _lightFontTheme.heading1SemiBold,
        headlineMedium: _lightFontTheme.heading2SemiBold,
        headlineSmall: _lightFontTheme.heading3SemiBold,
        titleLarge: _lightFontTheme.textLgBold,
        titleMedium: _lightFontTheme.textBaseBold,
        titleSmall: _lightFontTheme.textMdBold,
        bodyLarge: _lightFontTheme.textLgRegular,
        bodyMedium: _lightFontTheme.textBaseRegular,
        bodySmall: _lightFontTheme.textMdRegular,
        labelLarge: _lightFontTheme.textSmBold,
        labelMedium: _lightFontTheme.textSmRegular,
        labelSmall: _lightFontTheme.textXsRegular,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: _lightAppColorss.blueDefault,
          foregroundColor: _lightAppColorss.textWhite,
          disabledBackgroundColor: _lightAppColorss.inactiveButton,
          disabledForegroundColor: _lightAppColorss.textPrimary,
          textStyle: _lightFontTheme.textMdBold,
          elevation: 0,
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: _lightAppColorss.blueDefault,
          disabledForegroundColor: _lightAppColorss.textTertiary,
          textStyle: _lightFontTheme.textMdBold,
          side: BorderSide(color: _lightAppColorss.blueDefault),
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: _lightAppColorss.blueDefault,
          disabledForegroundColor: _lightAppColorss.textTertiary,
          textStyle: _lightFontTheme.textMdBold,
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        fillColor: _lightAppColorss.bgB0,
        filled: true,
        labelStyle: _lightFontTheme.textMdRegular
            .copyWith(color: _lightAppColorss.textTertiary),
        hintStyle: _lightFontTheme.textMdRegular
            .copyWith(color: _lightAppColorss.textTertiary),
        errorStyle: _lightFontTheme.textSmRegular
            .copyWith(color: _lightAppColorss.redDefault),
        border: OutlineInputBorder(
          borderSide: BorderSide(color: _lightAppColorss.grayQuaternary),
          borderRadius: BorderRadius.circular(8),
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _lightAppColorss.grayQuaternary),
          borderRadius: BorderRadius.circular(8),
        ),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _lightAppColorss.blueDefault),
          borderRadius: BorderRadius.circular(8),
        ),
        errorBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _lightAppColorss.redDefault),
          borderRadius: BorderRadius.circular(8),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _lightAppColorss.redDefault),
          borderRadius: BorderRadius.circular(8),
        ),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      ),
      extensions: [
        _lightAppColorss,
        _lightFontTheme,
      ],
    );
  }();

  static final dark = () {
    final defaultTheme = ThemeData.dark();

    return defaultTheme.copyWith(
      colorScheme: _darkAppColorss.toColorScheme(Brightness.dark),
      scaffoldBackgroundColor: _darkAppColorss.bgB0,
      appBarTheme: AppBarTheme(
        backgroundColor: _darkAppColorss.bgB0,
        titleTextStyle: _darkFontTheme.heading2Bold,
        elevation: 0,
      ),
      cardTheme: CardThemeData(
        color: _darkAppColorss.surfaceCard,
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8),
        ),
      ),
      textTheme: TextTheme(
        displayLarge: _darkFontTheme.heading1Bold,
        displayMedium: _darkFontTheme.heading2Bold,
        displaySmall: _darkFontTheme.heading3Bold,
        headlineLarge: _darkFontTheme.heading1SemiBold,
        headlineMedium: _darkFontTheme.heading2SemiBold,
        headlineSmall: _darkFontTheme.heading3SemiBold,
        titleLarge: _darkFontTheme.textLgBold,
        titleMedium: _darkFontTheme.textBaseBold,
        titleSmall: _darkFontTheme.textMdBold,
        bodyLarge: _darkFontTheme.textLgRegular,
        bodyMedium: _darkFontTheme.textBaseRegular,
        bodySmall: _darkFontTheme.textMdRegular,
        labelLarge: _darkFontTheme.textSmBold,
        labelMedium: _darkFontTheme.textSmRegular,
        labelSmall: _darkFontTheme.textXsRegular,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: _darkAppColorss.blueDefault,
          foregroundColor: _darkAppColorss.textWhite,
          disabledBackgroundColor: _darkAppColorss.inactiveButton,
          disabledForegroundColor: _darkAppColorss.textPrimary,
          textStyle: _darkFontTheme.textMdBold,
          elevation: 0,
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: _darkAppColorss.blueDefault,
          disabledForegroundColor: _darkAppColorss.textTertiary,
          textStyle: _darkFontTheme.textMdBold,
          side: BorderSide(color: _darkAppColorss.blueDefault),
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: _darkAppColorss.blueDefault,
          disabledForegroundColor: _darkAppColorss.textTertiary,
          textStyle: _darkFontTheme.textMdBold,
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        fillColor: _darkAppColorss.bgB0,
        filled: true,
        labelStyle: _darkFontTheme.textMdRegular
            .copyWith(color: _darkAppColorss.textTertiary),
        hintStyle: _darkFontTheme.textMdRegular
            .copyWith(color: _darkAppColorss.textTertiary),
        errorStyle: _darkFontTheme.textSmRegular
            .copyWith(color: _darkAppColorss.redDefault),
        border: OutlineInputBorder(
          borderSide: BorderSide(color: _darkAppColorss.grayQuaternary),
          borderRadius: BorderRadius.circular(8),
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _darkAppColorss.grayQuaternary),
          borderRadius: BorderRadius.circular(8),
        ),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _darkAppColorss.blueDefault),
          borderRadius: BorderRadius.circular(8),
        ),
        errorBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _darkAppColorss.redDefault),
          borderRadius: BorderRadius.circular(8),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderSide: BorderSide(color: _darkAppColorss.redDefault),
          borderRadius: BorderRadius.circular(8),
        ),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      ),
      extensions: [
        _darkAppColorss,
        _darkFontTheme,
      ],
    );
  }();
}

extension ThemeGetter on BuildContext {
  ThemeData get theme => Theme.of(this);

  TextTheme get textTheme => theme.textTheme;

  ColorScheme get colorScheme => theme.colorScheme;
}

extension AppThemeExtension on ThemeData {
  AppColorExtension get colors =>
      extension<AppColorExtension>() ?? AppTheme._lightAppColorss;

  AppFontThemeExtension get fonts =>
      extension<AppFontThemeExtension>() ?? AppTheme._lightFontTheme;
}
