import 'package:auto_route/auto_route.dart';
import 'package:defifundr_mobile/core/design_system/theme_extension/app_theme_extension.dart';
import 'package:defifundr_mobile/core/gen/assets.gen.dart';
import 'package:defifundr_mobile/core/routers/routers.dart';
import 'package:defifundr_mobile/core/shared/common/buttons/primary_button.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:pin_code_fields/pin_code_fields.dart';

@RoutePage()
class MoreTwoFaAuthCodeScreen extends StatefulWidget {
  const MoreTwoFaAuthCodeScreen({super.key});

  @override
  State<MoreTwoFaAuthCodeScreen> createState() =>
      _MoreTwoFaAuthCodeScreenState();
}

class _MoreTwoFaAuthCodeScreenState extends State<MoreTwoFaAuthCodeScreen> {
  final _otpController = TextEditingController();
  bool _isComplete = false;

  @override
  void dispose() {
    _otpController.dispose();
    super.dispose();
  }

  void _onConfirm() {
    if (_isComplete) {
      context.router.push(const TwoFaSetupCompleteRoute());
    }
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.theme.colors;
    final isLight = Theme.of(context).brightness == Brightness.light;

    return Scaffold(
      backgroundColor: isLight ? colors.bgB1 : colors.bgB0,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildAppBar(context),
            Expanded(
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: 20.w),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SizedBox(height: 8.h),
                    Text(
                      '2FA Auth Code',
                      style: context.theme.textTheme.headlineLarge?.copyWith(
                        fontSize: 24.sp,
                        color: colors.textPrimary,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    SizedBox(height: 4.h),
                    Text(
                      'Enter in the 6-digit code generated by the authenticator app',
                      style:
                          context.theme.textTheme.headlineMedium?.copyWith(
                        fontSize: 14.sp,
                        fontWeight: FontWeight.w400,
                        color: colors.textSecondary,
                      ),
                    ),
                    SizedBox(height: 32.h),
                    PinCodeTextField(
                      appContext: context,
                      length: 6,
                      controller: _otpController,
                      keyboardType: TextInputType.number,
                      animationType: AnimationType.fade,
                      useHapticFeedback: true,
                      showCursor: true,
                      autoDismissKeyboard: false,
                      autovalidateMode: AutovalidateMode.disabled,
                      backgroundColor: Colors.transparent,
                      pinTheme: PinTheme(
                        shape: PinCodeFieldShape.box,
                        borderRadius: BorderRadius.circular(12.r),
                        fieldHeight: 56.h,
                        fieldWidth: 48.w,
                        activeFillColor:
                            isLight ? colors.bgB0 : colors.bgB2,
                        inactiveFillColor:
                            isLight ? colors.bgB0 : colors.bgB2,
                        selectedFillColor:
                            isLight ? colors.bgB0 : colors.bgB2,
                        activeColor: colors.brandDefault,
                        inactiveColor: colors.grayTertiary,
                        selectedColor: colors.brandDefault,
                      ),
                      enableActiveFill: true,
                      textStyle: context.theme.textTheme.headlineLarge
                              ?.copyWith(
                            fontSize: 20.sp,
                            color: colors.textPrimary,
                            fontWeight: FontWeight.w600,
                          ) ??
                          const TextStyle(),
                      onChanged: (value) {
                        setState(() => _isComplete = value.length == 6);
                      },
                      onCompleted: (_) {
                        setState(() => _isComplete = true);
                      },
                    ),
                    const Spacer(),
                  ],
                ),
              ),
            ),
            Padding(
              padding: EdgeInsets.fromLTRB(20.w, 0, 20.w, 16.h),
              child: PrimaryButton(
                text: 'Confirm',
                isEnabled: _isComplete,
                onPressed: _isComplete ? _onConfirm : null,
              ),
            ),
            SizedBox(
                height:
                    MediaQuery.systemGestureInsetsOf(context).bottom + 8),
          ],
        ),
      ),
    );
  }

  Widget _buildAppBar(BuildContext context) {
    final colors = context.theme.colors;
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 8.w, vertical: 4.h),
      child: Align(
        alignment: Alignment.centerLeft,
        child: IconButton(
          icon: SvgPicture.asset(
            Assets.icons.arrowBack,
            colorFilter:
                ColorFilter.mode(colors.textPrimary, BlendMode.srcIn),
            width: 24.w,
            height: 24.w,
          ),
          onPressed: () => context.router.maybePop(),
        ),
      ),
    );
  }
}
