import 'package:defifundr_mobile/core/design_system/theme_extension/app_theme_extension.dart';
import 'package:defifundr_mobile/core/routers/routes_constant.dart';
import 'package:defifundr_mobile/modules/onboarding/presentation/multi_factor_authentication_screen/widgets/custom_back_button.dart';
import 'package:defifundr_mobile/core/shared/common_ui/buttons/help_button.dart';
import 'package:defifundr_mobile/modules/onboarding/presentation/multi_factor_authentication_screen/widgets/pin_input.dart';
import 'package:defifundr_mobile/modules/onboarding/presentation/multi_factor_authentication_screen/widgets/pin_keypad.dart';
import 'package:defifundr_mobile/modules/finance/presentation/bloc/withdraw_bloc/withdraw_bloc.dart';
import 'package:defifundr_mobile/modules/finance/presentation/bloc/withdraw_bloc/withdraw_event.dart';
import 'package:defifundr_mobile/modules/finance/presentation/bloc/withdraw_bloc/withdraw_state.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:go_router/go_router.dart';

class TwoFaAuthScreen extends StatefulWidget {
  const TwoFaAuthScreen({super.key});

  @override
  State<TwoFaAuthScreen> createState() => _TwoFaAuthScreenState();
}

class _TwoFaAuthScreenState extends State<TwoFaAuthScreen> {
  final List<String> _pin = [];
  final int _pinLength = 6;
  String? _errorMessage;

  void _onKeyPressed(String key) {
    if (_pin.length < _pinLength) {
      setState(() {
        _pin.add(key);
        _errorMessage = null;
      });

      if (_pin.length == _pinLength) {
        // TODO: Implement actual 2FA validation logic here
        // For now, we'll just simulate a successful 2FA
        Future.delayed(const Duration(seconds: 2), () {
          if (mounted) {
            // Complete the withdraw process
            context.read<WithdrawBloc>().add(const CompleteWithdraw());
            // Get withdraw details from bloc state
            final withdrawDetails =
                context.read<WithdrawBloc>().state.withdrawDetails;
            // Navigate to sent screen with withdraw details
            context.goNamed(
              RouteConstants.sent,
              extra: withdrawDetails,
            );
          }
        });
      }
    }
  }

  void _onBackspace() {
    if (_pin.isNotEmpty) {
      setState(() {
        _pin.removeLast();
        _errorMessage = null;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.theme.colors;
    final fonts = context.theme.fonts;

    return BlocBuilder<WithdrawBloc, WithdrawState>(
      builder: (context, state) {
        if (state.withdrawDetails == null) {
          return Scaffold(
            body: Center(
              child: Text('Error: Withdraw details not found'),
            ),
          );
        }

        return Scaffold(
          backgroundColor: Theme.of(context).brightness == Brightness.light
              ? colors.bgB0 // Light mode color
              : colors.bgB1,
          body: SafeArea(
            child: Column(
              children: [
                Padding(
                  padding:
                      EdgeInsets.symmetric(horizontal: 16.w, vertical: 8.h),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const CustomBackButton(),
                      const HelpButton(),
                    ],
                  ),
                ),
                Expanded(
                  child: Padding(
                    padding: EdgeInsets.symmetric(horizontal: 24.w),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        SizedBox(height: 16.h),
                        Text(
                          '2FA Auth Code',
                          style: fonts.heading2SemiBold,
                        ),
                        SizedBox(height: 8.h),
                        Text(
                          'Enter in the 6-digit code generated by the authenticator app',
                          style: fonts.textMdRegular.copyWith(
                            color: colors.textSecondary,
                          ),
                        ),
                        SizedBox(height: 32.h),
                        Text(
                          'Enter PIN',
                          style: fonts.textBaseMedium,
                        ),
                        SizedBox(height: 16.h),
                        PinInput(
                          pinValues: _pin,
                          activeIndex: _pin.length,
                          pinLength: _pinLength,
                          hasError: _errorMessage != null,
                        ),
                      ],
                    ),
                  ),
                ),
                PinKeypad(
                  onKeyPressed: _onKeyPressed,
                  onBackspace: _onBackspace,
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
